# Generated by Django 2.2.8 on 2020-01-03 12:21

from django.db import migrations


def forwards(apps, schema_editor):
    ApartmentSensor = apps.get_model('core', 'ApartmentSensor')  # noqa
    SensorAttribute = apps.get_model('core', 'SensorAttribute')  # noqa
    for sensor in ApartmentSensor.objects.all():
        for attr in SensorAttribute.objects.filter(apartment_sensor_values__apartment_sensor=sensor).distinct():
            apsen_attr = sensor.attributes.get_or_create(attribute=attr)[0]
            sensor.apartment_sensor_values.filter(attribute=attr).update(apartment_sensor_attribute=apsen_attr)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200103_1221'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
