# Generated by Django 2.2.8 on 2020-01-07 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200103_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='auth_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Token that SenseHel will include in all outgoing POST requests as authentication'),
        ),
        migrations.AddField(
            model_name='service',
            name='data_url',
            field=models.URLField(default='', help_text='URL to which sensor data should be POSTed'),
        ),
        migrations.AddField(
            model_name='service',
            name='preview_url',
            field=models.URLField(default='', help_text='URL that renders a compact subscription report for inclusion as iframe in user home view'),
        ),
        migrations.AddField(
            model_name='service',
            name='report_url',
            field=models.URLField(default='', help_text='URL to the main page presenting a subscription'),
        ),
        migrations.AddField(
            model_name='service',
            name='subscribe_url',
            field=models.URLField(default='', help_text='URL to which new subscriptions should be POSTed'),
        )
    ]
