# Generated by Django 2.2.8 on 2020-01-07 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_service_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='attributes',
            field=models.ManyToManyField(related_name='subscriptions', to='core.ApartmentSensorAttribute'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='registered',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
