# Generated by Django 2.2.8 on 2020-01-08 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_subscription_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='requires',
            field=models.ManyToManyField(help_text='At least one of these attributes must be included in any subscription to this service.', related_name='services', to='core.SensorAttribute'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.Service'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
