# Generated by Django 2.2.8 on 2020-01-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200108_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsensorvalue',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
