# Generated by Django 2.2.8 on 2020-01-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200116_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='unsubscribe_url',
            field=models.URLField(default='', help_text='URL to which unsubscribe requests should be POSTed'),
        ),
    ]
