# Generated by Django 2.2.8 on 2020-01-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_service_unsubscribe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='eula_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
