# Generated by Django 2.2.8 on 2020-10-13 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200122_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReportService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('img_logo_url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomReportSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_url', models.URLField(default='', help_text='URL to the main page presenting a subscription')),
                ('preview_url', models.URLField(default='', help_text='URL that renders a compact subscription report for inclusion as iframe in user home view')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.CustomReportService')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
